### ISSUE TITLE
 "manifest_version": 2 错误

### ISSUE THREAD

**Issue by loratadinetables** [seiuneko/JandanPicBoost#5]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by seiuneko** [comment]
Thanks for the issue. I know about the Manifest v2 deprecation and need to migrate to v3. But I’m busy with my final exams and will fix this next week. Please be patient and understanding.
