### ISSUE TITLE
啥时候上架chrome商店呀~

### ISSUE THREAD

**Issue by WhiteNightMo** [seiuneko/JandanPicBoost#6]
目前用的是加载已解压扩展程序的方式，但是每次浏览器关了就没了，真的很需要上架chrome商店呀，球球了。

**Comment by seiuneko** [comment]
等待审核中

**Comment by loratadinetables** [comment]
> 目前用的是加载已解压扩展程序的方式，但是每次浏览器关了就没了，真的很需要上架chrome商店呀，球球了。

已上架了。

**Comment by seiuneko** [comment]
https://chromewebstore.google.com/detail/pgkhddbbipclegkaheabhpahkifdaane
